### ISSUE TITLE
Cleanup interpolation matrix script

### ISSUE THREAD

**Issue by ammarhakim** [ammarhakim/postgkyl#4] opened 2020-03-09 16:39 UTC
The interpolation matrix generation script is a **huge mess!** Please use objects to do these things, rather than monster hard-to-read and maintain if-statements. Add a base class for interpolation generation, derive various classes to do one thing. Then the top-level can instantiate one of these classes and create the needed matrices.

**Comment by pcagas** [comment] 2020-03-10 15:54
Duplicate of #6

**Closed by pcagas** 2020-03-10 15:54 UTC
Labels: enhancement
